services:
  app:
    ports:
      - "8080:8080"
    build: ./
    volumes:
      - .:/home/developper/app
      - ~/.aws/:/home/developper/.aws/
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    privileged: true
